-- ============================================================
-- GENERATED FILE -- do not hand-edit. Built from the public coa-datamine
-- dataset (github.com/srhinos/coa-datamine) by a local generator script.
-- To fix a bad entry, add an override alias in Content.aliases.lua -- a
-- regenerate overwrites anything changed here directly. Content names,
-- mapIds and level ranges are Ascension/Blizzard game data, not original
-- work.
-- ============================================================
local ADDON, ns = ...
ns.C = ns.C or {}
ns.C.dungeons = {
  {name=[[Wailing Caverns]], mapId=43, isRaid=false, maxPlayers=10, levelMin=100, levelMax=100, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Scholomance]], mapId=289, isRaid=false, maxPlayers=5, levelMin=100, levelMax=100, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Ragefire Chasm]], mapId=389, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Deadmines]], mapId=36, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Shadowfang Keep]], mapId=33, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackfathom Deeps]], mapId=48, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Stormwind Stockade]], mapId=34, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Gnomeregan]], mapId=90, isRaid=false, maxPlayers=10, levelMin=100, levelMax=100, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Razorfen Kraul]], mapId=47, isRaid=false, maxPlayers=10, levelMin=25, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Scarlet Monastery - Graveyard]], mapId=189, isRaid=false, maxPlayers=10, levelMin=18, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Razorfen Downs]], mapId=129, isRaid=false, maxPlayers=10, levelMin=30, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Uldaman]], mapId=70, isRaid=false, maxPlayers=10, levelMin=100, levelMax=100, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Zul'Farrak]], mapId=209, isRaid=false, maxPlayers=10, levelMin=35, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Maraudon - Orange Crystals]], mapId=349, isRaid=false, maxPlayers=10, levelMin=35, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Sunken Temple]], mapId=109, isRaid=false, maxPlayers=10, levelMin=45, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackrock Depths - Prison]], mapId=230, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Lower Blackrock Spire]], mapId=229, isRaid=false, maxPlayers=10, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Dire Maul - East]], mapId=429, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Dire Maul - West]], mapId=429, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Dire Maul - North]], mapId=429, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Stratholme - Main Gate]], mapId=329, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Zul'Gurub]], mapId=309, isRaid=true, maxPlayers=20, levelMin=56, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Upper Blackrock Spire]], mapId=229, isRaid=false, maxPlayers=10, levelMin=45, levelMax=80, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackrock Caverns]], mapId=645, isRaid=false, maxPlayers=5, levelMin=35, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Molten Core]], mapId=409, isRaid=true, maxPlayers=40, levelMin=60, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackwing Lair]], mapId=469, isRaid=true, maxPlayers=40, levelMin=60, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Lower Scholomance]], mapId=289, isRaid=false, maxPlayers=5, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Upper Scholomance]], mapId=289, isRaid=false, maxPlayers=5, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Hellfire Ramparts]], mapId=543, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blood Furnace]], mapId=542, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Shattered Halls]], mapId=540, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Slave Pens]], mapId=547, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Underbog]], mapId=546, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Steamvault]], mapId=545, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Mana-Tombs]], mapId=557, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Auchenai Crypts]], mapId=558, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Sethekk Halls]], mapId=556, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Shadow Labyrinth]], mapId=555, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Ahn'Qiraj Ruins]], mapId=509, isRaid=true, maxPlayers=20, levelMin=60, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Ahn'Qiraj Temple]], mapId=531, isRaid=true, maxPlayers=25, levelMin=60, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Scarlet Monastery - Armory]], mapId=189, isRaid=false, maxPlayers=10, levelMin=20, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Scarlet Monastery - Cathedral]], mapId=189, isRaid=false, maxPlayers=10, levelMin=20, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Scarlet Monastery - Library]], mapId=189, isRaid=false, maxPlayers=10, levelMin=20, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Escape From Durnholde]], mapId=560, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Black Morass]], mapId=269, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Mechanar]], mapId=554, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Botanica]], mapId=553, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Arcatraz]], mapId=552, isRaid=false, maxPlayers=5, levelMin=58, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Karazhan]], mapId=532, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Magtheridon's Lair]], mapId=544, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Gruul's Lair]], mapId=565, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Tempest Keep]], mapId=550, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Serpentshrine Cavern]], mapId=548, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Hyjal Past]], mapId=534, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[Black Temple]], mapId=564, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Zul'Aman]], mapId=568, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Magisters' Terrace]], mapId=585, isRaid=false, maxPlayers=5, levelMin=100, levelMax=100, expansion=1, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Sunwell]], mapId=580, isRaid=true, maxPlayers=25, levelMin=70, levelMax=80, expansion=1, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Utgarde Keep]], mapId=574, isRaid=false, maxPlayers=25, levelMin=71, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Utgarde Pinnacle]], mapId=575, isRaid=false, maxPlayers=5, levelMin=77, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Azjol-Nerub]], mapId=601, isRaid=false, maxPlayers=5, levelMin=71, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Oculus]], mapId=578, isRaid=false, maxPlayers=5, levelMin=77, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Halls of Lightning]], mapId=602, isRaid=false, maxPlayers=5, levelMin=77, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Halls of Stone]], mapId=599, isRaid=false, maxPlayers=5, levelMin=75, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Culling of Stratholme]], mapId=595, isRaid=false, maxPlayers=5, levelMin=77, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Drak'Tharon Keep]], mapId=600, isRaid=false, maxPlayers=5, levelMin=72, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Gundrak]], mapId=604, isRaid=false, maxPlayers=5, levelMin=74, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Ahn'kahet: The Old Kingdom]], mapId=619, isRaid=false, maxPlayers=0, levelMin=71, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Violet Hold]], mapId=608, isRaid=false, maxPlayers=5, levelMin=73, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Nexus]], mapId=576, isRaid=false, maxPlayers=5, levelMin=71, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Naxxramas]], mapId=533, isRaid=true, maxPlayers=25, levelMin=80, levelMax=80, expansion=0, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Eye of Eternity]], mapId=616, isRaid=true, maxPlayers=5, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[The Obsidian Sanctum]], mapId=615, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[Vault of Archavon]], mapId=624, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[Ulduar]], mapId=603, isRaid=true, maxPlayers=5, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[Trial of the Champion]], mapId=650, isRaid=false, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Trial of the Grand Crusader]], mapId=649, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[mythic]]}},
  {name=[[Trial of the Crusader]], mapId=649, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[The Forge of Souls]], mapId=632, isRaid=false, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Pit of Saron]], mapId=658, isRaid=false, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Halls of Reflection]], mapId=668, isRaid=false, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Onyxia's Lair]], mapId=249, isRaid=true, maxPlayers=40, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Maraudon - Purple Crystals]], mapId=349, isRaid=false, maxPlayers=10, levelMin=35, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Maraudon - Pristine Waters]], mapId=349, isRaid=false, maxPlayers=10, levelMin=35, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Stratholme - Service Entrance]], mapId=329, isRaid=false, maxPlayers=5, levelMin=45, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackrock Depths - Upper City]], mapId=230, isRaid=false, maxPlayers=5, levelMin=51, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Icecrown Citadel]], mapId=631, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[The Headless Horseman]], mapId=189, isRaid=false, maxPlayers=10, levelMin=60, levelMax=82, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Frost Lord Ahune]], mapId=547, isRaid=false, maxPlayers=5, levelMin=70, levelMax=70, expansion=1, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Coren Direbrew]], mapId=230, isRaid=false, maxPlayers=5, levelMin=60, levelMax=80, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[The Crown Chemical Co.]], mapId=33, isRaid=false, maxPlayers=10, levelMin=60, levelMax=82, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Ruby Sanctum]], mapId=724, isRaid=true, maxPlayers=0, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[heroic]]}},
  {name=[[Tor'Watha]], mapId=1912, isRaid=false, maxPlayers=0, levelMin=23, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Vaults of Inquisition]], mapId=936, isRaid=false, maxPlayers=0, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Road to De Other Side]], mapId=937, isRaid=false, maxPlayers=0, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Naxxramas]], mapId=535, isRaid=true, maxPlayers=25, levelMin=80, levelMax=80, expansion=2, kind=[[raid]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Blackrock Depths - Manufactory]], mapId=230, isRaid=false, maxPlayers=5, levelMin=51, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Setis (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Azuregos (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Lethon (PvE)]], mapId=888, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Atal'Zul]], mapId=890, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[raid]], tiers={[[normal]]}},
  {name=[[Kazzak (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Will of Soggoth (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Kaldros Depthbreaker (PvE)]], mapId=891, isRaid=true, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Kaldros Depthbreaker (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Emeriss (PvE)]], mapId=973, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Emeriss (PvE)]], mapId=974, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Emeriss (PvE)]], mapId=975, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Emeriss (PvE)]], mapId=976, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Taerar (PvE)]], mapId=986, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Taerar (PvE)]], mapId=987, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Taerar (PvE)]], mapId=988, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Taerar (PvE)]], mapId=989, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Ysondre (PvE)]], mapId=990, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Ysondre (PvE)]], mapId=991, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Ysondre (PvE)]], mapId=992, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Ysondre (PvE)]], mapId=993, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Lethon (PvE)]], mapId=994, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Lethon (PvE)]], mapId=995, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Lethon (PvE)]], mapId=996, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Lethon (PvE)]], mapId=997, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Wailing Caverns - Pit of Fangs]], mapId=43, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Gnomeregan - Launch Bay]], mapId=90, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Uldaman - Map Chamber]], mapId=70, isRaid=false, maxPlayers=10, levelMin=30, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Uldaman - The Stone Vault]], mapId=70, isRaid=false, maxPlayers=10, levelMin=30, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Uldaman - Hall of the Crafters]], mapId=70, isRaid=false, maxPlayers=10, levelMin=30, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Wailing Caverns - Winding Chasm]], mapId=43, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Gnomeregan - Tinker's Court]], mapId=90, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Wailing Caverns - Crag of the Everliving]], mapId=43, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[mythic]]}},
  {name=[[Gnomeregan - Engineering Labs]], mapId=90, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Wailing Caverns - Dreamer's Rock]], mapId=43, isRaid=false, maxPlayers=10, levelMin=15, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[The Frozen Reach]], mapId=908, isRaid=false, maxPlayers=0, levelMin=81, levelMax=81, expansion=0, kind=[[dungeon]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Forgotten Mine]], mapId=1781, isRaid=false, maxPlayers=0, levelMin=25, levelMax=59, expansion=0, kind=[[dungeon]], tiers={[[normal]]}},
  {name=[[Korrim Snowgrave (PvE)]], mapId=889, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Wailing Caverns - Pit of the Fangs]], mapId=43, isRaid=false, maxPlayers=10, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[mythic]]}},
  {name=[[Shadowfang Keep - Halls of the Damned]], mapId=33, isRaid=false, maxPlayers=10, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[mythic]]}},
  {name=[[Shadowfang Keep - Arugal's Rise]], mapId=33, isRaid=false, maxPlayers=10, levelMin=60, levelMax=60, expansion=0, kind=[[dungeon]], tiers={[[mythic]]}},
  {name=[[Emeriss (PvE)]], mapId=880, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]]}},
  {name=[[Azuregos (PvE)]], mapId=881, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]], [[heroic]], [[mythic]]}},
  {name=[[Atal'Zul (PvE)]], mapId=890, isRaid=true, maxPlayers=40, levelMin=81, levelMax=81, expansion=0, kind=[[worldboss]], tiers={[[normal]], [[heroic]], [[mythic]]}},
}
ns.C.classes = {
  {name=[[Barbarian]], classId=12, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Energy]]},
  {name=[[Chronomancer]], classId=22, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Cultist]], classId=25, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[DeathKnight]], classId=6, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[RunicPower]]},
  {name=[[DemonHunter]], classId=nil, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=nil},
  {name=[[Druid]], classId=11, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[Guardian]], classId=18, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Energy]]},
  {name=[[Hunter]], classId=3, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[KnightOfXoroth]], classId=17, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Rage]]},
  {name=[[Mage]], classId=8, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[Monk]], classId=nil, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=nil},
  {name=[[Necromancer]], classId=23, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[RunicPower]]},
  {name=[[Paladin]], classId=2, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[Priest]], classId=5, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[Primalist]], classId=31, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Pyromancer]], classId=24, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Ranger]], classId=21, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Focus]]},
  {name=[[Reaper]], classId=30, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[RunicPower]]},
  {name=[[RebornDeathKnight]], classId=6, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[RunicPower]]},
  {name=[[RebornDruid]], classId=11, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornGeneral]], classId=nil, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=nil},
  {name=[[RebornHunter]], classId=3, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornMage]], classId=8, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornPaladin]], classId=2, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornPriest]], classId=5, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornRogue]], classId=4, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Energy]]},
  {name=[[RebornShaman]], classId=7, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornWarlock]], classId=9, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Mana]]},
  {name=[[RebornWarrior]], classId=1, tag=[[reborn]], realmHint=[[Bronzebeard - Warcraft Reborn]], powerType=[[Rage]]},
  {name=[[Rogue]], classId=4, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Energy]]},
  {name=[[Runemaster]], classId=32, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Shaman]], classId=7, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[SonOfArugal]], classId=nil, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=nil},
  {name=[[Starcaller]], classId=26, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Energy]]},
  {name=[[Stormbringer]], classId=16, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[SunCleric]], classId=27, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Tinker]], classId=28, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Venomancer]], classId=29, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[Warlock]], classId=9, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Mana]]},
  {name=[[Warrior]], classId=1, tag=[[vanilla]], realmHint=[[Area 52 - Free-Pick /shared]], powerType=[[Rage]]},
  {name=[[WitchDoctor]], classId=13, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[WitchHunter]], classId=15, tag=[[coa-custom]], realmHint=[[Rexxar/Vol'jin - Conquest of Azeroth]], powerType=[[Mana]]},
  {name=[[_other]], classId=nil, tag=[[meta]], realmHint=nil, powerType=nil},
}
